### ISSUE TITLE
Folder structure changed?

### ISSUE THREAD

**Issue by alexriabtsev** [ErikBjare/chatalysis#6]
Hello, Erik!

Thanks for nice tool!
But I didn't get it working unforunately.
I've extracted the archive into ./data/private and have subfolders facebook-myusername/messages/ and then folders:
- archived threads
- filtered threads
- inbox
- legacy threads
- message requests
- stickers used

Should it be like this? I tried to run `python3 main.py` and got 
name    msgs    days    words
------  ------  ------  -------
Messages sent by me: 0
year    # msgs    words    chars
------  --------  -------  -------
k    days    max streak    most used emoji
---  ------  ------------  -----------------

PS
`me` changed in main.py ;)

**Comment by ErikBjare** [comment]
Yeah, I haven't looked at it but I'd guess that a lot has changed in the export format (notably, there should now also be json available, so it should no longer need to parse the raw HTML). 

I haven't been running the code on the updated exports so it's unfortunately incompatible atm. I might look into fixing this in the future but not anytime soon. Feel free to investigate and make a PR if you have the time :)

**Comment by ErikBjare** [comment]
Found some time and fixed it today. Closing.

**Comment by alexriabtsev** [comment]
thanks Erik! Will check it :)
