### ISSUE TITLE
Add support for XMPP 

### ISSUE THREAD

**Issue by marclaporte** [ErikBjare/chatalysis#7]
https://xmpp.org/

This also explains why XMPP is important:
https://wikisuite.org/Why-Openfire

**Comment by ErikBjare** [comment]
"Add support for XMPP" would in practice be "Add support for one or more of the many XMPP clients" (which all have presumably different log formats).

If you want to contribute support, open a PR. I'll close this since I have no interest in pursuing this myself.

**Comment by guusdk** [comment]
I'm not sure _exactly_ what the use case of chatalysis is, and _exactly_ how it operates (I got dragged in here by @marclaporte :) ) but I can comment on the 'having to support many clients' assumption. I don't think that that's neccesarily true. By using [one](https://xmpp.org/extensions/xep-0313.html) of [two](https://xmpp.org/extensions/xep-0136.html) popular message archiving protocols, messages could be obtained from the XMPP domain in a standardized format.
